version: 0.2

env:
  variables:
    echo No_Variables: "No_Variables"

phases:
  pre_build:
    commands:
     - npm -v
     - echo npm init.
     - npm install -g newman
     - npm install -g newman-reporter-htmlextra
  build:
    commands:
     - ls -alrt
     - report=Auth_Report-$(date +%F-%H-%M-%S).html
     - newman -v
     - echo "Harsha"
  post_build:
    commands:
     - echo Changed this
